from tkinter import *
from tkinter.messagebox import *
from tkinter.filedialog import *
from Hamilton import Hamilton
import matplotlib.pyplot as plt
import random as rd
from tqdm import tqdm
import numpy as np

def recupHamilton():
	"""
	for i in tqdm(range(int(entrnb.get()))):
		x0 = rd.uniform(-4,4)
		y0 = rd.uniform(0,8)
		#x0 = 0.2
		#y0 = 0.2
		h = Hamilton(float(entrB.get()),float(entrA.get()),float(entrrho.get()),int(entrnb.get()),int(entrM.get()),x0,y0,float(entrdx.get()),float(entrdy.get()),float(entrT.get()),float(entrdt.get()))
		#x,y,b = h.dynamics()
		x,y = h.dynamicsb()
		#plt.plot(x,y,'.')
		plt.plot(np.mod(x,2*np.pi),np.mod(y,2*np.pi),'.')
		#plt.plot(b)
	"""
	me = float(entrme1.get())*(10**(int(entrme2.get())))
	h = Hamilton(float(entrB.get()),me,float(entrA.get()),float(entrrho.get()),int(entrnb.get()),int(entrM.get()),float(entrdx.get()),float(entrdy.get()),float(entrT.get()),float(entrdt.get()),choixInt.get(),choixOrdreGyro.get(),choixOrdreFLR.get(),int(entrnth.get()))
	x,y = h.dynamicsb()
	#plt.plot(x,y,'.')
	plt.plot(np.mod(x,2*np.pi),np.mod(y,2*np.pi),'.')
	plt.title("Ordre Gyro =" + str(choixOrdreGyro.get()) + " , A = " + entrA.get() + " , rho = " + entrrho.get() + " , M = " + entrM.get() + " , m/e = " + str(entrme1.get()) + "*10^" + str(entrme2.get()))
	plt.xlabel("x")
	plt.ylabel("y")
	plt.show()

fen1 = Tk()

Label(fen1, text = 'B :').grid(padx = 5, pady = 2, sticky =E)
Label(fen1, text = 'm/e :').grid(padx = 5, pady = 2, sticky =E)
Label(fen1, text = "nb particule test :").grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'A :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'rho :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'nombre de mode :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'Temps final :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'pas de temps :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'dx :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'dy :').grid(padx = 2, pady = 5, sticky =E)
Label(fen1, text = 'nombre theta :').grid(padx = 2, pady = 5, sticky =E)
entrB = Entry(fen1)
entrB.insert(0,'1')
entrme1 = Entry(fen1,width = 5)
entrme1.insert(0,'1')
entrme2 = Entry(fen1,width = 5)
entrme2.insert(0,'-7')
entrnb = Entry(fen1)
entrnb.insert(0,'50')
entrA = Entry(fen1)
entrA.insert(0,'0.4')
entrrho = Entry(fen1)
entrrho.insert(0,'0')
entrM = Entry(fen1)
entrM.insert(0,'1')
entrT = Entry(fen1)
entrT.insert(0,'100')
entrdt = Entry(fen1)
entrdt.insert(0,'50')
entrdx = Entry(fen1)
entrdx.insert(0,'0.00001')
entrdy = Entry(fen1)
entrdy.insert(0,'0.00001')
entrnth = Entry(fen1)
entrnth.insert(0,'20')
entrB.grid(row = 0, column = 1)
entrme1.grid(row = 1, column = 1,sticky = W)
Label(fen1, text = '*10^').grid(row=1,column = 1,padx = 5)
entrme2.grid(row = 1, column = 1,sticky = E)
entrnb.grid(row = 2, column = 1)
entrA.grid(row = 3, column = 1)
entrrho.grid(row = 4, column = 1)
entrM.grid(row = 5, column = 1)
entrT.grid(row = 6, column = 1)
entrdt.grid(row = 7, column = 1)
entrdx.grid(row = 8, column = 1)
entrdy.grid(row = 9, column = 1)
entrnth.grid(row = 10, column = 1)

choixInt = IntVar()
choixInt.set(2)
Label(fen1, text = 'Methode integration').grid(row = 0, column = 3, padx = 2, pady = 2, columnspan = 2)
odeint = Radiobutton(fen1, text = 'odeint', variable = choixInt, value=0)
solve_ivp = Radiobutton(fen1, text = 'solve_ivp', variable = choixInt, value = 1)
runge = Radiobutton(fen1, text = 'runge-kutta ordre 4', variable = choixInt, value=2)
leap = Radiobutton(fen1, text = 'leap-frog', variable = choixInt, value = 3)
odeint.grid(row = 1, column = 3, padx = 2, pady = 5)
solve_ivp.grid(row = 2, column = 3, padx = 5, pady = 5)
runge.grid(row = 3, column = 3, padx = 2, pady = 5)
leap.grid(row = 4, column = 3, padx = 5, pady = 5)

choixOrdreGyro = IntVar()
choixOrdreGyro.set(1)
Label(fen1, text = 'Ordre Gyro').grid(row = 1, column = 2, padx = 2, pady = 2, columnspan = 1)
ordre1Gyro = Radiobutton(fen1, text = 'Ordre 1', variable = choixOrdreGyro, value = 1)
ordre2Gyro = Radiobutton(fen1, text = 'Ordre 2', variable = choixOrdreGyro, value = 2)
ordre1Gyro.grid(row = 2, column = 2, padx = 2, pady = 5)
ordre2Gyro.grid(row = 3, column = 2, padx = 5, pady = 5)

choixOrdreFLR = IntVar()
choixOrdreFLR.set(1)
Label(fen1, text = 'Ordre FLR').grid(row = 6, column = 2, padx = 2, pady = 2, columnspan = 1)
ordre1FLR = Radiobutton(fen1, text = 'Tout ordre', variable = choixOrdreFLR, value = 1)
ordre2FLR = Radiobutton(fen1, text = 'Ordre 2', variable = choixOrdreFLR, value = 2)
ordre1FLR.grid(row = 7, column = 2, padx = 2, pady = 5)
ordre2FLR.grid(row = 8, column = 2, padx = 5, pady = 5)

bouton = Button(fen1, text ='Lancer simulation', command=recupHamilton)
bouton.grid(row = 12, columnspan = 2)

fen1.mainloop()